# Generated by Django 5.1.3 on 2024-12-02 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('fee_struct_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Title', max_length=100)),
                ('year', models.CharField(default='2024', max_length=5)),
                ('grade', models.CharField(choices=[('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6'), ('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9')], default='Grade 1', max_length=8)),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeStructureComponent',
            fields=[
                ('fee_struct_component_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(default='Description')),
                ('amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('term', models.CharField(choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3')], default='Term 1', max_length=6)),
                ('deadline', models.DateTimeField()),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('feeStructureParent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feeStructure.feestructure')),
            ],
        ),
    ]
